name: PlayerManager
main: net.meano.PlayerManager.PlayerManagerMain
version: 0.2
author: Meano
commands:
  PlayerManager:
    description: 玩家管理
    usage: /PlayerManager
    aliases: [pm]
    permission: PlayerManager.Command
    permission-message: 你没有权限

permissions:
  PlayerManager.*:
    default: op
    children:
      PlayerManager.Command: true
      PlayerManager.Whitelist: true
      PlayerManager.Award: true
  PlayerManager.Command:
    default: true
  PlayerManager.Whitelist:
    default: false
  PlayerManager.Award:
    default: false
  PlayerManager.Warn:
    default: false
